"""
ovnctl pcap -- port of ovn-pcap.sh

Captures traffic from VM logical ports using OVS port mirroring (SPAN).

For each target VM:
  1. a dedicated internal capture port is created on br-int
     (<mirror_prefix>-<vm>) -- its name never changes, unlike the VM's tap
  2. an OVS mirror copies the VM tap's ingress AND egress into it
  3. tcpdump writes rotated pcaps

The capture survives a VM restart: only the mirror's source port needs
re-pointing (--restart), while the tcpdump process and its output files
stay put.

DIRECT MODE: leave work_dir empty (or equal to directory) and tcpdump
writes straight into the destination -- no staging, no move. That is right
when the consumer takes files away itself. Its one requirement is that the
consumer triggers on CLOSE_WRITE, not on file creation.
"""

from __future__ import annotations

import argparse
import os
import pwd
import re
import shutil
import signal
import subprocess
import time
from pathlib import Path

from .. import libvirtutil, ovn
from ..context import Abort, Ctx
from ..inventory import VM, Inventory
from ..steps import add_step_args

NAME = "pcap"
HELP = "packet capture via OVS port mirroring"

RUNDIR = Path("/run/ovn-pcap")

REQUIRED_CFG = (
    "pcap:compress", "pcap:directory", "pcap:enabled", "pcap:max_files",
    "pcap:min_free_mb", "pcap:mirror_prefix", "pcap:naming",
    "pcap:rotate_seconds", "pcap:snaplen", "pcap:subdirs", "pcap:targets",
    "topology:br_int",
)

# Generated per --start. -z passes exactly one argument and gives us nowhere
# to put configuration, so the destination, compress setting and retention
# limit are baked into the hook itself.
ROTATE_HOOK = r"""#!/bin/sh
# Generated by ovnctl pcap. Do not edit -- rewritten on every --start.
set -u
DEST="{dest}"
COMPRESS="{compress}"
KEEP="{keep}"
OWNER="{owner}"
POST="{post}"
KEEPORIG="{keep_original}"
PATTERN="{pattern}"
WORK="{work}"
MOVE="{move}"

f="${{1:-}}"
[ -n "${{f}}" ] && [ -f "${{f}}" ] || exit 0

# Post-processing. Runs on the closed file, before compression, because
# both tools want an uncompressed pcap.
#
# NOTE ON EVIDENCE: this DELETES packets. If keep_original is true the
# untouched capture is preserved alongside as *.orig.pcap, and that is the
# default -- a filtered capture cannot be un-filtered, and there is no
# record inside it of what was removed.
case "${{POST}}" in
    dedupe)
        [ "${{KEEPORIG}}" = "true" ] && cp -p "${{f}}" "${{f%.pcap}}.orig.pcap"
        if editcap -d "${{f}}" "${{f}}.pp" 2>/dev/null; then
            mv -f "${{f}}.pp" "${{f}}"
        else
            rm -f "${{f}}.pp"
            echo "editcap -d failed on $(basename "${{f}}")" >> "${{DEST}}/.postprocess-failed.log"
        fi
        ;;
    no-retrans)
        [ "${{KEEPORIG}}" = "true" ] && cp -p "${{f}}" "${{f%.pcap}}.orig.pcap"
        if tshark -2 -r "${{f}}" -w "${{f}}.pp" \
             -Y "not tcp.analysis.retransmission and not tcp.analysis.fast_retransmission and not tcp.analysis.spurious_retransmission" 2>/dev/null; then
            mv -f "${{f}}.pp" "${{f}}"
        else
            rm -f "${{f}}.pp"
            echo "tshark filter failed on $(basename "${{f}}")" >> "${{DEST}}/.postprocess-failed.log"
        fi
        ;;
esac

if [ "${{COMPRESS}}" = "true" ]; then
    gzip -f "${{f}}" || exit 1
    f="${{f}}.gz"
fi

b=$(basename "${{f}}")

# Direct mode: the file is already where it belongs. Nothing to move.
if [ "${{MOVE}}" != "true" ]; then
    if [ -n "${{OWNER}}" ]; then
        chown "${{OWNER}}" "${{f}}" 2>/dev/null \
            || echo "chown ${{OWNER}} failed (no CAP_CHOWN) on ${{b}}" >> "${{DEST}}/.chown-failed.log"
    fi
    exit 0
fi

# Two steps on purpose. work_dir and the archive are usually different
# filesystems, so mv is a copy-then-unlink and anything reading the archive
# could otherwise pick up a half-written pcap. Landing on a dotted name
# first means the only thing that appears under the real name is a rename
# within one filesystem, which is atomic.
mv -f "${{f}}" "${{DEST}}/.inflight.${{b}}" || exit 1
mv -f "${{DEST}}/.inflight.${{b}}" "${{DEST}}/${{b}}" || exit 1

# The preserved original, if post-processing kept one.
for o in "${{WORK}}"/*.orig.pcap "${{WORK}}"/*.orig.pcap.gz; do
    [ -f "${{o}}" ] || continue
    ob=$(basename "${{o}}")
    mv -f "${{o}}" "${{DEST}}/.inflight.${{ob}}" 2>/dev/null \
        && mv -f "${{DEST}}/.inflight.${{ob}}" "${{DEST}}/${{ob}}" 2>/dev/null
done

# Ownership, if requested. Changing owner to another UID needs CAP_CHOWN,
# which this hook does not have unless tcpdump is running as root. The
# failure is recorded rather than swallowed.
if [ -n "${{OWNER}}" ]; then
    chown "${{OWNER}}" "${{DEST}}/${{b}}" 2>/dev/null \
        || echo "chown ${{OWNER}} failed (no CAP_CHOWN) on ${{b}}" >> "${{DEST}}/.chown-failed.log"
fi

# Retention, if enabled. 0 keeps everything, which is the default: these
# are engagement captures and silently deleting evidence is worse than
# filling a disk you are already monitoring.
if [ "${{KEEP}}" -gt 0 ] 2>/dev/null; then
    ls -1t ${{DEST}}/${{PATTERN}} 2>/dev/null | tail -n +$((KEEP + 1)) | \
        while IFS= read -r old; do rm -f "${{old}}"; done
fi
exit 0
"""


def register(subparsers) -> argparse.ArgumentParser:
    p = subparsers.add_parser(NAME, help=HELP, description=__doc__,
                              formatter_class=argparse.RawDescriptionHelpFormatter)
    g = p.add_mutually_exclusive_group()
    g.add_argument("--start", action="store_true", help="begin capturing")
    g.add_argument("--stop", action="store_true",
                   help="stop and remove mirrors")
    g.add_argument("--restart", action="store_true",
                   help="re-resolve taps and restart")
    g.add_argument("--status", action="store_true",
                   help="what is running, file sizes, disk free (default)")
    add_step_args(p)
    p.set_defaults(func=main)
    return p


def fs_safe(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]", "_", text)


def safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", text)


class Pcap:
    def __init__(self, ctx: Ctx):
        self.ctx = ctx
        c = ctx.config

        self.enabled = c.cfg_bool("pcap", "enabled", False)
        self.directory = c.cfg("pcap", "directory")
        work = c.cfg_opt("pcap", "work_dir", "/tmp/ovn-pcap-live")

        # DIRECT MODE: empty work_dir (or equal to directory) means tcpdump
        # writes straight into the destination -- no staging, no move.
        if not work or work == self.directory:
            self.work_dir = self.directory
            self.direct = True
        else:
            self.work_dir = work
            self.direct = False

        self.archive_max = c.cfg_opt("pcap", "archive_max_files", "0")
        self.archive_reader = c.cfg_opt("pcap", "archive_reader", "")
        self.archive_owner = c.cfg_opt("pcap", "archive_owner", "")
        self.post = c.cfg_opt("pcap", "post_process", "none")
        self.keep_original = c.cfg_opt("pcap", "keep_original", "true")

        self.targets = c.cfg("pcap", "targets")
        self.snaplen = c.cfg("pcap", "snaplen")
        self.filter = c.cfg_opt("pcap", "filter", "")
        self.rotate = c.cfg("pcap", "rotate_seconds")
        self.max_files = c.cfg("pcap", "max_files")
        self.prefix = c.cfg("pcap", "mirror_prefix")
        self.compress = c.cfg_opt("pcap", "compress", "true")
        self.drop_user_cfg = c.cfg_opt("pcap", "drop_user", "tcpdump")
        self.min_free_mb = c.cfg_int("pcap", "min_free_mb")
        self.subdirs = c.cfg_bool("pcap", "subdirs", True)
        self.file_prefix = c.cfg_opt("pcap", "file_prefix", "internal")
        self.naming = c.cfg("pcap", "naming")   # auto | inventory | libvirt

        self.br_int = c.cfg("topology", "br_int")

        self.inv = Inventory(c)
        self.vms = self._load_targets()

        self.have_virsh = libvirtutil.available(ctx)
        self.mac_tap: dict[str, str] = {}
        self.mac_domain: dict[str, str] = {}
        self.name_override = self._load_name_map()
        self.drop_user = "root"

    # ------------------------------------------------------------------
    def _load_targets(self) -> list[VM]:
        vms = self.inv.select(self.targets)
        if not vms:
            raise Abort(f"No VMs matched pcap.targets='{self.targets}'.")
        return vms

    def _load_name_map(self) -> dict[str, str]:
        """Explicit inventory-name -> libvirt-domain overrides from [vm_names]."""
        out: dict[str, str] = {}
        for entry in self.ctx.cfg_list("vm_names", "map"):
            parts = entry.split()
            if len(parts) >= 2:
                out[parts[0]] = parts[1]
        return out

    def build_virsh_map(self) -> None:
        if self.have_virsh:
            self.mac_tap, self.mac_domain = libvirtutil.mac_maps(self.ctx)

    # ------------------------------------------------------------------
    def tap_for(self, vm: VM) -> str:
        """The local tap carrying this logical port.

        Resolved from OVS, not libvirt: ovn-controller binds a port by
        matching external-ids:iface-id on a local interface, so OVS holds
        the definitive mapping -- and it works on a host with no libvirt
        CLI, which is what previously made every VM look "not running" and
        get silently skipped.
        """
        ctx = self.ctx
        tap = ovn.iface_for_iface_id(ctx, vm.uuid)
        if tap:
            return tap
        tap = ctx.qout("ovs-vsctl", "--bare", "--columns=name", "find",
                       "Interface", f"external-ids:attached-mac={vm.mac_lc}")
        if tap.strip():
            return tap.splitlines()[0].strip()
        # libvirt is only a fallback now, for a tap with no iface-id set.
        return self.mac_tap.get(vm.mac_lc, "")

    def tap_absent_reason(self, vm: VM) -> str:
        """Explain a missing tap instead of asserting the VM is off."""
        if ovn.port_binding_chassis(self.ctx, vm.uuid):
            return "bound to a chassis, but no local interface carries its iface-id"
        return "logical port not bound -- VM powered off, or its tap is not on br-int"

    def label_for(self, vm: VM) -> str:
        """The human-facing name used for directories and filenames.

        Explicit map wins, then the live libvirt domain, then the inventory
        name.
        """
        if self.naming == "inventory":
            return fs_safe(vm.name)
        if self.naming == "libvirt":
            label = self.name_override.get(vm.name) or self.mac_domain.get(vm.mac_lc)
            if not label:
                self.ctx.warn(f"No libvirt domain known for {vm.name} "
                              "(not running, and no [vm_names].map entry).")
                self.ctx.warn("  Falling back to the inventory name for its "
                              "capture path.")
                label = vm.name
            return fs_safe(label)
        label = (self.name_override.get(vm.name)
                 or self.mac_domain.get(vm.mac_lc)
                 or vm.name)
        return fs_safe(label)

    # ------------------------------------------------------------------
    def vm_dir(self, label: str) -> Path:
        base = Path(self.directory)
        return base / label if self.subdirs else base

    def vm_work_dir(self, label: str) -> Path:
        base = Path(self.work_dir)
        return base / label if self.subdirs else base

    # ------------------------------------------------------------------
    # permissions
    # ------------------------------------------------------------------
    def resolve_drop_user(self) -> str:
        """Which account tcpdump drops to.

        RHEL/Oracle Linux package it as "tcpdump"; Debian/Ubuntu use "pcap".
        """
        if not self.drop_user_cfg or self.drop_user_cfg == "root":
            return "root"
        try:
            pwd.getpwnam(self.drop_user_cfg)
            return self.drop_user_cfg
        except KeyError:
            pass
        try:
            pwd.getpwnam("pcap")
            return "pcap"
        except KeyError:
            return ""

    def grant_capture_dir(self, directory: Path, user: str,
                          archive: bool = False) -> None:
        """tcpdump drops privileges (-Z) BEFORE it creates its output file,
        so the capture directory must be writable by that user and not
        merely by root. This is the single most common reason captures fail
        with "Permission denied" while the directory plainly exists.

        Access is granted by POSIX ACL rather than chown: these directories
        are provisioned and ACL'd elsewhere, so taking ownership would fight
        whatever set them up and would quietly strip access other accounts
        depend on.
        """
        ctx = self.ctx
        ctx.run("mkdir", "-p", str(directory))
        if user in ("root", ""):
            return

        if not ctx.have("setfacl"):
            ctx.warn(f"setfacl not found -- cannot grant {user} write access to "
                     f"{directory}.")
            ctx.warn("Install it (dnf install acl), or tcpdump will fail the moment")
            ctx.warn("it drops privileges, with the directory looking perfectly fine.")
            return

        # -m MODIFIES the ACL: existing named users, the group entry and the
        # owner are all left alone. Never use --set here -- it replaces the
        # whole ACL, which is how you remove someone else's access without
        # ever seeing an error.
        #
        # rwx, not rw. On a directory 'x' is what permits entering it at all;
        # a directory granted rw without x cannot be written to.
        if not ctx.run("setfacl", "-m", f"u:{user}:rwx", str(directory)):
            ctx.warn(f"setfacl failed on {directory} -- captures will not be able "
                     "to write.")
            ctx.warn("Usually the filesystem is mounted without ACL support.")
            return

        # Default entry, so rotated files -- and any per-VM subdirectory made
        # later -- inherit the grant. Capital X means execute for directories
        # only: a new subdir stays traversable while the pcaps stay
        # non-executable.
        ctx.run("setfacl", "-d", "-m", f"u:{user}:rwX", str(directory))

        # Optional second grantee: whatever picks the captures up. This is
        # how an upload process gets full read/write/delete WITHOUT anyone
        # having to own the files.
        if archive and self.archive_reader:
            if not ctx.run("setfacl", "-m", f"u:{self.archive_reader}:rwx",
                           str(directory)):
                ctx.warn(f"Could not grant {self.archive_reader} access to "
                         f"{directory}.")
            ctx.run("setfacl", "-d", "-m", f"u:{self.archive_reader}:rwX",
                    str(directory))

    def grant_rundir(self, user: str) -> None:
        """RUNDIR holds pid files and the generated rotate hooks.

        The hook is executed by tcpdump AFTER -Z has dropped privileges, so
        the capture user has to traverse this directory and execute the hook
        in it. The mode is set explicitly rather than left to root's umask:
        on a hardened build with umask 077 the directory would come out
        0700, the hook would not be executable, and rotations would quietly
        stop moving files while tcpdump carried on capturing.
        """
        ctx = self.ctx
        ctx.run("mkdir", "-p", str(RUNDIR))
        ctx.run("chmod", "0750", str(RUNDIR))
        if user in ("root", "") or not ctx.have("setfacl"):
            return
        # rx, not rwx: the capture user runs the hook, it never writes here.
        ctx.run("setfacl", "-m", f"u:{user}:rx", str(RUNDIR))

    # ------------------------------------------------------------------
    def write_rotate_hook(self, sname: str, dest: Path, pattern: str,
                          work: Path, move: bool) -> str:
        hook = RUNDIR / f"rotate-{sname}.sh"
        if self.ctx.dry_run:
            return str(hook)
        hook.write_text(ROTATE_HOOK.format(
            dest=dest, compress=self.compress, keep=self.archive_max,
            owner=self.archive_owner, post=self.post,
            keep_original=self.keep_original, pattern=pattern, work=work,
            move="true" if move else "false",
        ), encoding="utf-8")
        # Owned by root and never written by the capture user, so read+execute
        # via ACL is enough and avoids making it world-executable.
        hook.chmod(0o750)
        if self.drop_user not in ("root", "") and self.ctx.have("setfacl"):
            if not self.ctx.q("setfacl", "-m", f"u:{self.drop_user}:rx",
                              str(hook)).ok:
                self.ctx.warn(f"Could not ACL {hook}; rotations may not move files.")
        return str(hook)

    # ------------------------------------------------------------------
    def check_disk(self) -> None:
        ctx = self.ctx
        if ctx.dry_run:
            return
        for d in {self.work_dir, self.directory}:
            try:
                usage = shutil.disk_usage(d)
                free_mb = usage.free // (1024 * 1024)
            except OSError:
                continue
            if free_mb < self.min_free_mb:
                ctx.warn(f"Only {free_mb} MB free at {d} "
                         f"(minimum {self.min_free_mb} MB).")
            else:
                ctx.log(f"Disk: {free_mb} MB free at {d}.")

        # A tmpfs work_dir spends RAM, not disk, and loses anything unrotated
        # on reboot. Reasonable for capture performance, but only if
        # rotate_seconds keeps the open file small.
        fstype = ctx.qout("df", "-PT", self.work_dir)
        if fstype:
            rows = fstype.splitlines()
            if len(rows) > 1 and len(rows[1].split()) > 1 \
                    and rows[1].split()[1] == "tmpfs":
                ctx.warn(f"{self.work_dir} is tmpfs -- the open capture file is "
                         "held in RAM")
                ctx.warn("until it rotates, and is lost on reboot. With "
                         f"rotate_seconds={self.rotate}")
                ctx.warn(f"and snaplen={self.snaplen}, size that against available "
                         "memory,")
                ctx.warn("or point work_dir at disk-backed storage.")

        # archive_max_files is what caps the archive. max_files only ever
        # caps the work directory, because files leave it on every rotation.
        if self.archive_max == "0":
            ctx.log("Archive retention: unlimited (pcap.archive_max_files: 0).")
            ctx.log(f"  {self.directory} grows without bound -- watch it, or set "
                    "a limit.")

    # ------------------------------------------------------------------
    def _preflight_ownership(self) -> None:
        """archive_owner only works if the rotate hook has CAP_CHOWN, and the
        hook inherits tcpdump's DROPPED privileges. Say so now rather than
        letting every rotation append to a log nobody reads."""
        ctx = self.ctx
        if self.archive_owner and self.drop_user != "root":
            want_u = self.archive_owner.split(":")[0]
            ctx.warn(f"pcap.archive_owner is {self.archive_owner}, but the rotate "
                     "hook runs")
            ctx.warn(f"as '{self.drop_user}' and cannot change ownership to "
                     "another UID.")
            ctx.warn(f"Files will land owned by '{self.drop_user}'. Three ways "
                     "to fix it:")
            ctx.warn(f"  1. pcap.archive_reader: {want_u}  -- grants that UID")
            ctx.warn("     full rw by ACL. No ownership change needed, and it is")
            ctx.warn("     almost always what an upload process actually requires.")
            ctx.warn(f"  2. pcap.drop_user: <the uid-{want_u} account> -- tcpdump then")
            ctx.warn("     creates the files as that user from the outset.")
            ctx.warn("  3. A root wrapper invoked via sudo -- see pcap.archive_owner")
            ctx.warn("     in the settings file for the sudoers entry.")

        # If an ownership was requested, guarantee it or refuse. Getting this
        # wrong is silent -- the captures are written, everything looks
        # healthy, and the consumer rejects them for reasons that show up
        # nowhere here.
        if not self.archive_owner:
            if self.drop_user != "root":
                try:
                    info = pwd.getpwnam(self.drop_user)
                    ctx.log(f"Captures will be created as {self.drop_user} "
                            f"({info.pw_uid}:{info.pw_gid}).")
                except KeyError:
                    pass
            return

        want_u, _, want_g = self.archive_owner.partition(":")
        if self.drop_user == "root":
            ctx.log(f"Captures created as root, then chown'd to "
                    f"{self.archive_owner} on rotation.")
            return
        try:
            info = pwd.getpwnam(self.drop_user)
            have_u, have_g = str(info.pw_uid), str(info.pw_gid)
        except KeyError:
            have_u = have_g = "?"
        if (have_u, have_g) == (want_u, want_g):
            ctx.log(f"Captures will be created as {self.drop_user} "
                    f"({have_u}:{have_g}) -- matches")
            ctx.log("pcap.archive_owner, so no chown is needed anywhere.")
            return
        raise Abort(
            f"pcap.archive_owner is {self.archive_owner}, but drop_user "
            f"'{self.drop_user}' is {have_u}:{have_g}. The rotate hook runs with\n"
            "tcpdump's dropped privileges and cannot chown to another UID, so the\n"
            f"captures would silently be written as {have_u}:{have_g}.\n\n"
            f"Point drop_user at an account that IS {want_u}:{want_g}:\n"
            f"  getent passwd {want_u}          # is one already there?\n"
            f"  groupadd -g {want_g} ovnpcap 2>/dev/null\n"
            f"  useradd -r -o -u {want_u} -g {want_g} -s /sbin/nologin -M ovnpcap\n"
            "  # then set  pcap.drop_user: ovnpcap\n\n"
            "-o permits a duplicate UID, so this coexists with whatever account\n"
            f"already holds {want_u}. -r -M -s /sbin/nologin keeps it a service\n"
            "identity with no login and no home directory."
        )

    def _warn_direct_mode(self) -> None:
        ctx = self.ctx
        if not self.direct:
            return
        ctx.log(f"DIRECT mode: writing straight into {self.directory}, no "
                "staging move.")
        # A consumer watching this directory sees the file the instant
        # tcpdump creates it, and it then grows for a whole rotation period.
        ctx.warn(f"Whatever ingests {self.directory} must trigger on CLOSE_WRITE, "
                 "not on")
        ctx.warn("file creation -- tcpdump keeps each file open for "
                 f"rotate_seconds ({self.rotate}s)")
        ctx.warn("and it grows the whole time. A watcher that reads on create will")
        ctx.warn("ingest a truncated pcap. If yours polls instead, set work_dir")
        ctx.warn("back to a staging path: the two-step move removes the race.")
        if self.compress == "true":
            ctx.warn("pcap.compress is true in direct mode. The .pcap is closed and")
            ctx.warn("visible BEFORE gzip replaces it with .pcap.gz, so a watcher can")
            ctx.warn("ingest the same capture twice. Set compress: false here.")
        if self.archive_max != "0":
            ctx.warn("archive_max_files is set in direct mode -- this would be "
                     "deleting")
            ctx.warn("files the consumer may not have ingested yet. Set it to 0 and")
            ctx.warn("let the consumer manage its own directory.")

    def _check_post_process(self) -> None:
        """Post-processing needs wireshark-cli, and it runs as the capture
        user. Check now: a missing binary would otherwise show up only as a
        growing .postprocess-failed.log inside the archive."""
        ctx = self.ctx
        if self.post == "none":
            pass
        elif self.post == "dedupe":
            if not ctx.have("editcap"):
                ctx.warn("pcap.post_process is 'dedupe' but editcap is not "
                         "installed (dnf install wireshark-cli).")
        elif self.post == "no-retrans":
            if not ctx.have("tshark"):
                ctx.warn("pcap.post_process is 'no-retrans' but tshark is not "
                         "installed (dnf install wireshark-cli).")
            ctx.warn("post_process 'no-retrans' runs a two-pass tshark over every")
            ctx.warn("rotated file. That is CPU-heavy and grows with capture size --")
            ctx.warn(f"check it completes well inside rotate_seconds ({self.rotate}s)")
            ctx.warn("or hooks will overlap.")
        else:
            ctx.warn(f"pcap.post_process '{self.post}' is not recognised; expected "
                     "none|dedupe|no-retrans.")
            ctx.warn("No post-processing will be applied.")

        if self.post != "none" and self.keep_original != "true":
            ctx.warn("pcap.keep_original is false: post-processing will DELETE "
                     "packets with")
            ctx.warn("no preserved copy. For engagement captures this is usually the")
            ctx.warn("wrong call -- a filtered pcap cannot be un-filtered.")

    # ------------------------------------------------------------------
    def do_start(self) -> int:
        ctx = self.ctx
        if not self.enabled:
            raise Abort(
                "pcap.enabled is false in ovn-settings.yaml -- refusing to start.\n"
                "Set it to true, or this would capture without it being recorded "
                "in config."
            )
        ctx.require_cmd("tcpdump")

        if not ovn.br_exists(ctx, self.br_int) and not ctx.dry_run:
            raise Abort(f"{self.br_int} does not exist.")

        if not self.have_virsh:
            ctx.log("virsh not present -- resolving taps from OVS, naming by "
                    "inventory.")

        self.drop_user = self.resolve_drop_user()
        if not self.drop_user:
            ctx.warn(f"User '{self.drop_user_cfg}' does not exist -- running "
                     "tcpdump as root.")
            ctx.warn("That skips its privilege drop. Create the user, or set")
            ctx.warn("pcap.drop_user: root in the settings to make this explicit.")
            self.drop_user = "root"

        self.grant_capture_dir(Path(self.work_dir), self.drop_user)
        self.grant_capture_dir(Path(self.directory), self.drop_user, archive=True)

        self._preflight_ownership()
        self._warn_direct_mode()
        self.grant_rundir(self.drop_user)
        self._check_post_process()
        self.check_disk()

        ctx.dr_head(f"Capture ports and mirrors on {self.br_int}")

        started = skipped = 0
        for vm in self.vms:
            result = self._start_one(vm)
            if result is True:
                started += 1
            elif result is False:
                skipped += 1

        if ctx.dry_run:
            return 0

        print("")
        if started == 0:
            ctx.warn(f"No captures started -- no VM in '{self.targets}' has a tap "
                     f"on {self.br_int}.")
            ctx.err(f"No captures started ({skipped} target(s) had no resolvable "
                    "tap).")
            ctx.err("Check that the VMs are running and their ports are bound:")
            ctx.err("  ovs-vsctl --columns=name,external_ids list Interface "
                    "| grep -A1 iface-id")
            ctx.err("  ovnctl pcap --status")
            return 1

        ctx.say(f"Capture ports are OVS ports on {self.br_int}, visible with:")
        ctx.say(f"  ovs-vsctl show          (Port {self.prefix}-*)")
        ctx.say("  ovs-vsctl list mirror   (the mirror objects)")
        ctx.say("They are deliberately absent from `ovnctl show`: no iface-id is")
        ctx.say("set, so OVN never sees them and will not try to bind them.")
        ctx.finish(f"{started} capture(s) started, {skipped} skipped -- "
                   f"{self.max_files} x {self.rotate}s per VM")
        return 0

    def _start_one(self, vm: VM) -> bool | None:
        """True started, False skipped, None already running."""
        ctx = self.ctx
        sname = safe_name(vm.name)
        mirport = f"{self.prefix}-{sname}"
        mirname = f"mirror-{sname}"
        label = self.label_for(vm)

        tap = self.tap_for(vm)
        if not tap:
            if ctx.dry_run:
                tap = f"<tap-for-{vm.name}>"
            else:
                # Always say why. This used to skip silently when virsh was
                # absent, producing an empty capture directory and no
                # explanation anywhere.
                ctx.warn(f"{vm.name} ({vm.ip}): {self.tap_absent_reason(vm)} "
                         "-- skipping.")
                return False

        # Stable capture interface -- name is independent of the tap.
        ctx.run("ovs-vsctl", "--may-exist", "add-port", self.br_int, mirport,
                "--", "set", "interface", mirport, "type=internal")
        ctx.run("ip", "link", "set", mirport, "up")

        # Replace any previous mirror for this VM.
        if ovn.mirror_exists(ctx, mirname):
            ctx.run("ovs-vsctl", "--", "--id=@m", "get", "mirror", mirname,
                    "--", "remove", "bridge", self.br_int, "mirrors", "@m")
            ctx.run("ovs-vsctl", "--if-exists", "destroy", "mirror", mirname)

        # Both directions of the VM's tap into the capture port.
        ctx.run("ovs-vsctl",
                "--", "--id=@src", "get", "port", tap,
                "--", "--id=@out", "get", "port", mirport,
                "--", "--id=@m", "create", "mirror", f"name={mirname}",
                "select-src-port=@src", "select-dst-port=@src",
                "output-port=@out",
                "--", "add", "bridge", self.br_int, "mirrors", "@m")

        outdir = self.vm_dir(label)
        workdir = self.vm_work_dir(label)

        # Both directories need the capture user's ACL: tcpdump writes into
        # work, and the rotate hook -- also running as that user -- creates
        # into the archive and unlinks from work.
        self.grant_capture_dir(workdir, self.drop_user)
        self.grant_capture_dir(outdir, self.drop_user, archive=True)

        # Filename: <prefix>_<vm-label>_<capture-interface>_<timestamp>
        #
        # The timestamp is a bare 14-digit YYYYMMDDHHMMSS -- no separators,
        # so the name sorts lexically in time order and `ls` alone gives
        # chronological sequence. tcpdump runs this through strftime when -G
        # rotates the file. Including the interface matters now that a VM can
        # be captured on more than one mirror port.
        fpattern = f"{self.file_prefix}_{label}_{mirport}_*.pcap*"
        outfile = (f"{workdir}/{self.file_prefix}_{label}_{mirport}"
                   "_%Y%m%d%H%M%S.pcap")

        # No hook at all when direct mode has nothing left to do: no move, no
        # compression, no post-processing, no chown.
        hook = ""
        if (not self.direct or self.compress == "true" or self.post != "none"
                or self.archive_owner):
            hook = self.write_rotate_hook(sname, outdir, fpattern, workdir,
                                          move=not self.direct)

        pidfile = RUNDIR / f"{sname}.pid"
        if self._pid_alive(pidfile):
            ctx.log(f"  {vm.name}: capture already running "
                    f"(pid {pidfile.read_text().strip()}).")
            return None

        td = ["tcpdump", "-i", mirport, "-n", "-U",
              "-s", str(self.snaplen),
              "-G", str(self.rotate), "-W", str(self.max_files),
              "-Z", self.drop_user,
              "-w", outfile]
        # -z is the rotate hook, not gzip: the hook compresses (if enabled)
        # and then moves the file to the archive. Only one -z is possible, so
        # the two jobs share it.
        if hook:
            td += ["-z", hook]
        if self.filter:
            td.append(self.filter)

        if ctx.dry_run:
            ctx.run(*td)
            return None

        return self._spawn(vm, td, pidfile, sname, tap, mirport, workdir,
                           outdir, label)

    def _spawn(self, vm: VM, td: list[str], pidfile: Path, sname: str,
               tap: str, mirport: str, workdir: Path, outdir: Path,
               label: str) -> bool:
        ctx = self.ctx
        errfile = RUNDIR / f"{sname}.err"
        try:
            with open(errfile, "wb") as errfh:
                proc = subprocess.Popen(
                    td, stdout=subprocess.DEVNULL, stderr=errfh,
                    start_new_session=True,
                )
        except OSError as exc:
            ctx.warn(f"{vm.name}: could not start tcpdump: {exc}")
            return False

        pidfile.write_text(f"{proc.pid}\n", encoding="utf-8")
        time.sleep(0.3)
        if proc.poll() is not None:
            ctx.warn(f"{vm.name}: tcpdump failed to start. See {errfile}")
            try:
                head = errfile.read_text(errors="replace").splitlines()[:3]
                ctx.note_stderr("\n".join(head))
            except OSError:
                pass
            return False

        if label != vm.name:
            ctx.log(f"  {vm.name} ({vm.ip}) [libvirt: {label}]: tap {tap} -> "
                    f"{mirport} -> {workdir}/ -> {outdir}/")
        else:
            ctx.log(f"  {vm.name} ({vm.ip}): tap {tap} -> {mirport} -> "
                    f"{workdir}/ -> {outdir}/")
        return True

    # ------------------------------------------------------------------
    @staticmethod
    def _pid_alive(pidfile: Path) -> bool:
        try:
            pid = int(pidfile.read_text().strip())
        except (OSError, ValueError):
            return False
        try:
            os.kill(pid, 0)
            return True
        except OSError:
            return False

    def do_stop(self) -> int:
        ctx = self.ctx
        ctx.dr_head("Stop captures and remove mirrors")
        stopped = 0

        for vm in self.vms:
            sname = safe_name(vm.name)
            mirport = f"{self.prefix}-{sname}"
            mirname = f"mirror-{sname}"
            pidfile = RUNDIR / f"{sname}.pid"

            if pidfile.exists():
                if self._pid_alive(pidfile):
                    pid = pidfile.read_text().strip()
                    if ctx.dry_run:
                        ctx.run("kill", pid)
                    else:
                        try:
                            os.kill(int(pid), signal.SIGTERM)
                            ctx.changes += 1
                            stopped += 1
                            ctx.log(f"  stopped capture for {vm.name} (pid {pid}).")
                        except (OSError, ValueError):
                            pass
                ctx.run("rm", "-f", str(pidfile))
            ctx.run("rm", "-f", str(RUNDIR / f"rotate-{sname}.sh"))

            if ovn.mirror_exists(ctx, mirname):
                ctx.run("ovs-vsctl", "--", "--id=@m", "get", "mirror", mirname,
                        "--", "remove", "bridge", self.br_int, "mirrors", "@m")
                ctx.run("ovs-vsctl", "--if-exists", "destroy", "mirror", mirname)
                ctx.log(f"  removed mirror {mirname}.")

            if mirport in ovn.list_ports(ctx, self.br_int):
                ctx.run("ovs-vsctl", "--if-exists", "del-port", self.br_int,
                        mirport)
                ctx.log(f"  removed capture port {mirport}.")

        if ctx.dry_run:
            return 0

        # The file tcpdump had OPEN never rotated, so its hook never ran.
        # Move whatever is left before anything else touches the work
        # directory -- otherwise the most recent capture of every VM is left
        # behind, which is the one most likely to matter.
        for vm in self.vms:
            label = self.label_for(vm)
            self.sweep_work_dir(self.vm_work_dir(label), self.vm_dir(label))

        ctx.log(f"Stopped {stopped} capture(s). Captures are kept in "
                f"{self.directory}.")
        return 0

    def sweep_work_dir(self, wdir: Path, dest: Path) -> None:
        ctx = self.ctx
        if not wdir.is_dir() or wdir == dest:
            return
        for pattern in ("*.pcap", "*.pcap.gz"):
            for f in sorted(wdir.glob(pattern)):
                inflight = dest / f".inflight.{f.name}"
                try:
                    dest.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(f), str(inflight))
                    inflight.replace(dest / f.name)
                    ctx.log(f"  swept {f.name} -> {dest}/")
                except OSError:
                    ctx.warn(f"  could not move {f} to {dest} -- left in place.")

    # ------------------------------------------------------------------
    def do_status(self) -> int:
        ctx = self.ctx
        print("")
        print("=== Capture status ===")
        print(f"enabled: {self.enabled}   targets: {self.targets}   "
              f"directory: {self.directory}")
        if self.have_virsh:
            print(f"libvirt: available   bridge: {self.br_int}")
        else:
            print("libvirt: not installed -- taps resolved from OVS, names from "
                  "the inventory")
        print(f"rotation: {self.max_files} files x {self.rotate}s   "
              f"snaplen: {self.snaplen}   filter: {self.filter or '<none>'}")
        print("")
        print(f"{'VM':<10} {'LIBVIRT':<14} {'TAP':<10} {'CAPTURE PORT':<13} "
              f"{'MIRROR':<6} {'PID':<6} {'FILES':<8} DIRECTORY")

        for vm in self.vms:
            label = self.label_for(vm)
            sname = safe_name(vm.name)
            mirport = f"{self.prefix}-{sname}"
            pidfile = RUNDIR / f"{sname}.pid"
            state = pidfile.read_text().strip() if self._pid_alive(pidfile) else "-"
            mirror = "active" if ovn.mirror_exists(ctx, f"mirror-{sname}") else "-"
            tap = self.tap_for(vm) or "-"
            vdir = self.vm_dir(label)
            files = len(list(vdir.glob(f"{self.file_prefix}_{label}_*.pcap*"))) \
                if vdir.is_dir() else 0
            print(f"{vm.name:<10} {label:<14} {tap:<10} {mirport:<13} "
                  f"{mirror:<6} {state:<6} {files:<8} {vdir}")

        print("")
        base = Path(self.directory)
        if not base.is_dir():
            print(f"{self.directory} does not exist yet.")
            print("")
            return 0

        total = ctx.qout("du", "-sh", self.directory).split()
        free = ctx.qout("df", "-Ph", self.directory).splitlines()
        free_col = free[1].split()[3] if len(free) > 1 else "?"
        print(f"Total: {total[0] if total else '?'}   free: {free_col}")
        print("")
        print("Most recent capture per VM:")
        for vm in self.vms:
            label = self.label_for(vm)
            vdir = self.vm_dir(label)
            candidates = sorted(vdir.glob(f"{self.file_prefix}_{label}_*.pcap*"),
                                key=lambda p: p.stat().st_mtime, reverse=True) \
                if vdir.is_dir() else []
            if candidates:
                latest = candidates[0]
                size = latest.stat().st_size
                print(f"  {vm.name:<10} {latest}  ({_human(size)})")
            else:
                print(f"  {vm.name:<10} (no captures yet)")
        print("")
        return 0


def _human(size: int) -> str:
    for unit in ("B", "K", "M", "G", "T"):
        if size < 1024:
            return f"{size:.0f}{unit}"
        size /= 1024.0
    return f"{size:.0f}P"


def main(ctx: Ctx, args: argparse.Namespace) -> int:
    ctx.load_config("ovn-pcap")
    ctx.require_cfg(*REQUIRED_CFG)

    ctx.require_root()
    ctx.require_cmd("ovs-vsctl")

    cmd = Pcap(ctx)
    cmd.build_virsh_map()

    if getattr(args, "list_steps", False):
        print("`ovnctl pcap` has modes rather than steps:")
        print("  --start    create mirrors and begin capturing")
        print("  --stop     stop tcpdump, remove mirrors, sweep the work dir")
        print("  --restart  stop then start (re-resolves taps after a VM reboot)")
        print("  --status   show what is running (default)")
        return 0

    if args.start:
        return cmd.do_start()
    if args.stop:
        return cmd.do_stop()
    if args.restart:
        rc = cmd.do_stop()
        return cmd.do_start() or rc
    return cmd.do_status()
